server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
