spring:
  datasource:
    url: jdbc:h2:mem:app;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

# Console H2
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console

logging:
  level:
    org.hibernate.SQL: warn
